<a href="https://colab.research.google.com/github/Dkepffl/2022-1-ESAA/blob/main/Assignment/Assignment0314.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
import numpy as np

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [2]:
Z = np.arange('2016-07', '2016-08', dtype = 'datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [7]:
def compute_above(A,B):
  A= A.astype(float)
  B= B.astype(float)
  np.add(A, B, out = B) # Elementwise addition
  np.divide(A, 2, out = A) # output을 A에 저장.
  np.negative(A, out = A)
  np.multiply(A, B, out = A)
  return A

A = np.random.randint(1,10, size = (3,3))
B = np.random.randint(1,10, size = (3,3))
print(compute_above(A,B))

[[-56.   -1.   -6. ]
 [-10.5  -3.  -58.5]
 [-40.  -49.  -15. ]]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [10]:
Z = np.random.uniform(0,10,10)
print(Z)

print(Z - Z%1) # 소수부분을 뺀다.
print(Z // 1) 
print(np.floor(Z)) # 내림 함수
print(Z.astype(int)) # 형변환

[3.52289409 7.30742401 5.1990697  3.66122056 4.81164952 3.25188489
 9.41669546 0.55742309 7.06991458 8.45954962]
[3. 7. 5. 3. 4. 3. 9. 0. 7. 8.]
[3. 7. 5. 3. 4. 3. 9. 0. 7. 8.]
[3. 7. 5. 3. 4. 3. 9. 0. 7. 8.]
[3 7 5 3 4 3 9 0 7 8]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [17]:
Z = np.arange(5)
I = np.zeros((5,5))
np.add(I, Z, out= I)
print(I)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [28]:
def gene_10int():
  X = np.random.randint(0,100, size = 10)
  return X

print(gene_10int())

[76 28 12 16 75 27 42 20 36  4]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [31]:
Z = np.random.random(10)
print(Z)

[0.19907766 0.69785925 0.27317757 0.52696312 0.53338761 0.09260116
 0.57043515 0.8246693  0.95673288 0.57916521]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [32]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.0390216  0.17063945 0.18831734 0.28006073 0.56698482 0.6277131
 0.70259308 0.76362302 0.79879399 0.87275575]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [34]:
Z = np.arange(10)
np.add.reduce(Z)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [39]:
A = np.random.randint(1,10, size = (3,3))
B = np.random.randint(1,10, size = (3,3))
print('A :\n',A,'\n B :\n', B)

np.equal(A,B)

A :
 [[5 2 9]
 [2 7 8]
 [9 7 9]] 
 B :
 [[7 4 9]
 [6 9 5]
 [5 6 5]]


array([[False, False,  True],
       [False, False, False],
       [False, False, False]])

#### 43. Make an array immutable (read-only) (★★☆)

In [40]:
Z = np.zeros(10)
Z.flags.writeable = False # 읽기 전용
Z[0] = 1 # assignment destination is read-only

ValueError: ignored

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [44]:
Z = np.random.randint(1,10, size = (10,2))
X = Z[:,0] # column1 = X
Y = Z[:,1] # column2 = Y

# convert to polar
R = np.sqrt(X**2 + Y**2)
T = np.arctan2(Y,X) # angle
for i in range(10):
  print('({} , {})'.format(R[i],T[i]))

(9.219544457292887 , 0.21866894587394195)
(7.615773105863909 , 1.1659045405098132)
(10.63014581273465 , 0.8519663271732721)
(3.1622776601683795 , 1.2490457723982544)
(5.0990195135927845 , 1.373400766945016)
(8.06225774829855 , 0.5191461142465229)
(10.0 , 0.6435011087932844)
(5.830951894845301 , 0.5404195002705842)
(10.0 , 0.9272952180016122)
(10.816653826391969 , 0.5880026035475675)


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [47]:
Z = np.random.randint(1,10, size = 10)
print(Z)
Z[Z.argmax()] = 0
print(Z)

[7 8 1 5 2 1 9 8 6 1]
[7 8 1 5 2 1 0 8 6 1]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [67]:
Z = np.zeros((5,5),[('x', float),('y',float)])
Z['x'],Z['y'] = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [59]:
X = np.random.randint(1,10, size = (5,5))
Y = np.random.randint(1,10, size = (5,5))

C = 1.0/np.subtract(X,Y)
print(C)


[[        inf -0.16666667  0.125       0.5        -0.5       ]
 [ 0.33333333 -1.         -1.         -0.16666667 -0.33333333]
 [-1.          0.2         1.          0.16666667 -0.25      ]
 [ 0.25       -0.2         0.2        -1.          0.125     ]
 [ 0.33333333  0.14285714 -0.5         0.5         0.25      ]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: RuntimeWarning: divide by zero encountered in true_divide
  after removing the cwd from sys.path.


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [61]:
for dtype in [np.int8, np.int32, np.int64]:
  print(np.iinfo(dtype).min)
  print(np.iinfo(dtype).max)
for dtype in [ np.float32, np.float64]:
  print(np.finfo(dtype).min)
  print(np.finfo(dtype).max)
  print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [63]:
np.set_printoptions(threshold = float("inf"))
Z = np.zeros((16,16))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [65]:
Z = np.arange(100)
v = np.random.uniform(0,100)
print(v)
index = (np.abs(Z-v)).argmin() # 절댓값이 가장 작은 index를 찾아 넣는다.
print(Z[index])

60.2207130541499
60
