<a href="https://colab.research.google.com/github/Dkepffl/2022-1-ESAA/blob/main/Assignment/Assignment0311.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 01 머신러닝의 개념
___
- **머신러닝(Machine Learning)** :  '데이터'를 기반으로 패턴을 학습하고 결과를 예측하는 알고리즘 기법
- 기존에는 매우 복잡한 현실 세계의 조건들로 인해 해결하기 어려웠던 문제들을 머신러닝을 이용해 해결 가능하다.
- 데이터마이닝, 영상 인식, 음성 인식, 자연어 처리에서 개발자가 데이터나 업무 로직의 특성을 직접 고려한 프로그램을 만들 때 난이도와 개발 복잡도가 너무 높아지는 문제를 머신러닝을 이용해 해결할 수 있다.

### | 머신러닝의 분류
___
- **지도학습(Supercised Learning)**
  + 분류(Classification) : 여러 특징 데이터를 기반으로 데이터의 종류를 예측
  + 회귀(Regression) : 여러 특징 데이터를 기반으로 연속값과 같은 수치를 예측
  + 그 외에도 추천 시스템, 텍스트분석, NLP(Natural Language Processing) 등이 있다.
- **비지도학습(Un-Supercised Learning)**
  + 군집화(clustering) : 학습 데이터가 가진 패턴을 발견해 비슷한 패턴을 가진 성질의 데이터를 모으는 방법
  + 차원 축소
- **강화학습(Reinforcement Learning)** : 어떤 환경의 상태에서 어떤 행동을 해야 보상을 가장 많이 받을 수 있는지 구하는 방법. 지도 학습이나 비지도 학습과 달리 학습 데이터가 주어지지 않은 채, 에이전트는 시행착오 만을 통해 학습한다.



## 02 파이썬 머신러닝 생태계를 구성하는 주요 패키지
___
- 머신러닝 패키지 : 사이킷런(Scikit-Learn). 텐서플로(Tensorflow) 등
- 행렬/선형대수/통계 패키지 : 넘파이(NumPy),사이파이(SciPy) 
- 데이터 핸들링 : 판다스(Pandas)
- 시각화 : Matplotlib



## 03 넘파이
___
- 머신러닝의 주요 알구리즘은 선형대수학과 통계학 등에 기반한다.
- 넘파이 패키지는 파이썬에서 선형대수학 기반의 프로그램을 쉽게 만들 수 있도록 지원하는 대표적인 패키지
- 구글의 대표적인 딥러닝 프레임워크인 텐서플로는 배열 연산 수행 속도를 개선하고 넘파이와도 호환된다.
- 넘파이는 배열 기반의 연산은 물론이고 다양한 데이터 핸들링 기능을 제공한다. 다만 편의성과 다양한 API 지원 측면에서 판다스보다 아쉬운 부분이 많다.
- **넘파이를 이해하는 것은 파이썬 기반의 머신러닝에서 매우 중요**하다 : 많은 머신러닝 알고리즘이 넘파이 기반으로 작성되어있으며, 입출력 데이터의 타입이 넘파이의 배열 타입이기 때문이다.


### | 넘파이 ndarray 개요
___
- **NumPY Module Import** : `as np`를 추가해 약어로 모듈을 표현해주는 게 관례
```python 
import numpy as np
```
  + 넘파이의 기반 데이터 타입은 **ndarry**
  + ndarray를 이용해 Multi-dimension 배열을 쉽게 생성하고 다양한 연산을 수행할 수 있다.

- 넘파이의 **array() 함수** : List와 같이 다양한 인자를 입력받아서 ndarry로 변환한다.
```python
array 1 = np.array(['element1','element2'])
```
  + ndarray 배열의 `shape` 변수는 ndarrya의 크기, 즉 row와 column의 수를 tuple 형태로 가지고 있다.
  + 아래 예제에서 array1과 array3는 동일한 차원의 데이터가 아니라는 점을 유의해야한다. 
  + 이 때, `ndarray.ndim`을 이용하면 array의 차원을 확인할 수 있다.
 

In [ ]:
import numpy as np

array1 = np.array([1,2,3]) # 1X3 배열
print('array1 type: ', type(array1))
print('array1 array 형태: ', array1.shape)  #row 1개, column 3개인 1차원 데이터

array2 = np.array([[1,2,3],[2,3,4]]) # 2X3 배열
print('array2 type: ', type(array2))
print('array2 array 형태: ', array2.shape) #row 1개, column 3개인 1차원 데이터

array3 = np.array([[1,2,3]]) # 1X3 배열. 대괄호가 2개
print('array3 type: ', type(array3))
print('array3 array 형태: ', array3.shape) # row 1개, column 3개인 2차원 데이터

array1 type:  <class 'numpy.ndarray'>
array1 array 형태:  (3,)
array2 type:  <class 'numpy.ndarray'>
array2 array 형태:  (2, 3)
array3 type:  <class 'numpy.ndarray'>
array3 array 형태:  (1, 3)


In [ ]:
print('array1: {:0}차원, array2: {:1}차원, array3: {:2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1: 1차원, array2: 2차원, array3:  2차원


### | ndarray의 데이터 타입
___
- ndarray 내의 데이터값은 숫자(ex. int형, float형), 문자열(stirng), 불(bool) 등 모두 가능하다.
- list와 다르게 ndaarry 내의 데이터 타입은 그 연산의 특성상 같은 데이터 타입만 가능하다.
- ndarray 내의 데이터 타입은 `dtype` 속성으로 확인할 수 있다.

In [ ]:
list1 = [1, 2, 3]
print(type(list1))

array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


- 다른 데이터 유형이 섞여있는 list를 ndarrya로 변경하면, **데이터 크기가 더 큰 데이터 타입**으로 자료형을 일괄 변환한다.
  + 아래 예제에서 list2의 데이터들은 모두 string형으로 변환되어었고, list3의 데이터들은 모두 float형으로 변경되었다.

In [ ]:
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U21
[1. 2. 3.] float64


- **astype()** method : ndarray 내 데이터값의 타입 변경이 가능하다.
  + 대용량의 데이터를 만들 때 많은 메모리가 사용되기 때문에, 보통 메모리를 절약하기 위해 데이터 타입을 변경한다.
  + 파이썬 기반의 머신러닝 알고리즘은 대부분 메모리로 데이터를 전체 로딩한 다음 이를 기반으로 알고리즘을 적용하기 때문에 대용량의 데이터를 로딩할 때는 수행속도가 느려지거나 메모리 부족으로 오류가 발생할 수 있다. 따라서 불필요하게 큰 데이터의 경우, 데이터값의 타입 변경을 하는 편이 좋다.

In [ ]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64') # int형 데이터를 float형으로 변환하여 저장
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32') # float형을 다시 int형으로 변환
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1]) # float형 배열
array_int2 = array_float1.astype('int32') 
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


### | ndarray를 편하게 생성하기 - arange, zeros, ones
___
- 특정 크기와 차원을 가진 ndarray를 연속값이나 0 또는 1로 초기화하고 싶을 때, `arange()`, `zeros()`, `ones()`를 사용한다.
  + 테스트용 데이터를 만드는 경우
  + 대규모의 데이터를 일괄적으로 초기화해야 할 경우
- **arange()** 함수 : 지정한 범위의 값을 순차적으로 ndarray의 값으로 반환한다.
  + `range()`와 유사한 기능을 한다.
  + 아래와 같이 stop 값을 지정해주면 0부터 'N-1'까지의 연속 숫자값으로 구성된 1차원 ndarray를 만들어준다.
  ```python 
  np.arange(N)
  ```
 + 아래와 같이 `range`처럼 start값과 숫자의 간격(step)을 설정해줄 수 있다.
  ```python 
  np.arange(A, B, step)
  ```

In [ ]:
import numpy as np

sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[2 5 8]
int64 (3,)


- **zeros()** 함수 : 모든 값을 0으로 채운 ndarray를 반환한다.
  + `shpae`값을 tuple 형태로 입력해야 한다.
  + datatype을 지정해주지 않으면 default로 float64 형의 데이터를 가진 ndarray를 반환한다.
  ```python 
  np.zeros((row, column), dtype = 'datatype')
  ```
- **ones()** 함수 : 모든 값을 1으로 채운 ndarray를 반환한다.
 + `zeros()`처럼, `shpae`값을 tuple 형태로 입력해야 한다.
 + 역시, datatype을 지정해주지 않으면 default로 float64 형의 데이터를 가진 ndarray를 반환한다.
  ```python 
  np.ones((row, column), dtype = 'datatype')
  ```

In [ ]:
zero_array = np.zeros((3, 2), dtype = 'int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape, '\n')

one_array = np.ones((3, 2)) # datatype을 입력하지 않아, default로 float64 형 데이터를 값으로 반환한다.
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2) 

[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


### | ndarray의 차원과 크기를 변경하는 reshape()
___
- **reshape()** 메서드 : ndarray를 특정 차원 및 크기로 변환한다.
  + 아래와 같이 변환하려는 크기(row, column)를 변수로 입력하면 된다.
  ```python 
  'ndarray'.reshape(row,column)
  ```


In [ ]:
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2,5)
print('array2:\n', array2)

array3 = array1.reshape(5,2)
print('array3:\n', array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


- 지정한 사이즈로 변경이 불가능할 경우, 아래와 같이 오류가 발생한다.

In [ ]:
array1.reshape(4,3)

ValueError: ignored

- **reshape()**의 인자로 -1을 사용하면 원래 ndarray와 호환되는 새로운 shape로 변환한다.
  + 아래 예제에서, array1은 1차원 ndarray로 0~9까지의 데이터를 가지고 있다.
  + array1.reshape(-1,5)은 array1과 호환되는 2차원 ndarray이되, column의 수가 5인 ndarray로 변환하는 것이다.
  + array1.reshape(5,-1)은 반대로 array1과 호환되는 2차원 ndarray이되, row의 수가 5인 ndarray로 변환하는 것이다.
  + 다만, -1을 사용하더라도 호환될 수 없는 형태는 변환할 수 없다.
    * (EX) 10개의 1차원 데이터를 4개의 column을 가진 2차원 데이터 변경

In [ ]:
array1 = np.arange(10)
print(array1)

array2 = array1.reshape(-1,5)
print(array2)
print('array2 shape:', array2.shape)
print()

array3 = array1.reshape(5,-1)
print(array3)
print('array3 shape', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
array2 shape: (2, 5)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
array3 shape (5, 2)


In [ ]:
array1 = np.arange(10)
array4 = array1.reshape(-1,4)

ValueError: ignored

- 원본 ndarray가 어떤 형태라도 **reshape(-1,1)**는 2차원이고 column이 1개인 ndarray로 변환한다.
  + `stack`이나 `concat`으로 여러 개의 ndarray를 결합할 때, ndarray의 형태를 통일하기 위해 유용하게 사용된다.
  + 아래 예제는 다른 차원의 데이터를 2차원 ndarray로 변경하는 예제이다.

In [ ]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2)) # 3차원 배열
print('array3d: \n', array3d.tolist())

# 3차원 ndarray를 2차원으로 변환
array5 = array3d.reshape(-1,1)
print('array5 : \n', array5.tolist()) # list로 변경
print('array5 shape:', array5.shape)
print()
# 1차원 ndarray를 2차원으로 변환
array6 = array1.reshape(-1,1)
print('array6 : \n', array6.tolist()) # list로 변경
print('array6 shape:', array6.shape)

array3d: 
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5 : 
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)

array6 : 
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


### | 넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱(Indexing)
___
- **인덱싱(indexing)**을 이용하면 ndarray 내의 일부 데이터 세트나 특정 데이터만을 선택할 수 있다.
1. **특정 데이터만 추출**(단일 값 추출) : 원하는 위치의 인덱스 값을 지정하면 해당 위치의 데이터를 반환
```python
value = array[i]
```
  + index는 0부터 시작한다.
  + list나 dictionary처럼 index로 negative integer를 이용할 수도 있다.

In [ ]:
array1 = np.arange(start=1, stop=10) # [1, 2, 3, 4, 5, 6, 7, 8, 9]인 1차원 ndarray 생성
print('array1: ', array1)

value = array1[2] # 3
print('value: ', value)
print(type(value)) # value의 datatye은 ndarray가 아니라 int

array1:  [1 2 3 4 5 6 7 8 9]
value:  3
<class 'numpy.int64'>


In [ ]:
print('맨 뒤의 값: ', array1[-1], ' 맨 뒤에서 두 번째 값: ', array1[-2])

맨 뒤의 값:  9  맨 뒤에서 두 번째 값:  8


In [ ]:
#index를 이용한 ndarray 데이터 값 수정
array1[0] = 9
array1[8] = 0
print('array1: ', array1)

array1:  [9 2 3 4 5 6 7 8 0]


In [32]:
# n차원 ndarray에서 단일 값 추출(n>=2)
array1d = np.arange(start = 1, stop = 10)
array2d = array1d.reshape(3,3)
print(array2d)

print('(row=0, col=0) index가 가리키는 값 : ', array2d[0,0]) # axis 0 : row 방향, axis 1 : column 방향
print('(row=0, col=1) index가 가리키는 값 : ', array2d[0,1])
print('(row=1, col=0) index가 가리키는 값 : ', array2d[1,0])
print('(row=2, col=2) index가 가리키는 값 : ', array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index가 가리키는 값 :  1
(row=0, col=1) index가 가리키는 값 :  2
(row=1, col=0) index가 가리키는 값 :  4
(row=2, col=2) index가 가리키는 값 :  9


2. **슬라이싱(Slicing)** : **' : '**을 이용해 연속된 인덱스 상의 ndarray를 추출
```python
array2 = array1[A:B]
```
  + 위와 같이 입력하면, A 인덱스에서 (B-1)인덱스까지의 데이터 세트를 반환한다.
  + 슬라이싱으로 추출된 데이터 세트의 datatype은 모두 ndarray이다.
  + 시작, 종료 index는 생략이 가능하다
    1. `array[:B]` : 시작 인덱스를 생략하면 자동으로 0 인덱스부터 시작한다. 
    2. `array[A:]` : 종료 인덱스를 생략하면 자동으로 맨 마지막 인덱스까지의 값을 반환한다.
    3. `array[:]` : 자동으로 모든 인덱스의 값을 반환한다.
  + 2차원 ndarray에서는 ' , '를 이용하여 row와 column 인덱스를 지정한다.

In [33]:
array1 = np.arange(1,10)
array4 = array1[:3] 
print(array4) # [1,2,3]

array5 = array1[3:] 
print(array5) # [4,5,6,7,8,9]

array6 = array1[:] 
print(array6) # [1,2,3,4,5,6,7,8,9]

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [35]:
# 2차원 ndarray에서의 슬라이싱

array1d = np.arange(1,10)
array2d = array1d.reshape(3,3)
print('array2d : \n', array2d)

print('aarray2d[0:2,0:2] : \n', array2d[0:2,0:2])
print('aarray2d[1:3,1:3] : \n', array2d[1:3,1:3])
print('aarray2d[1:3,:] : \n', array2d[1:3,:])
print('aarray2d[:,:] : \n', array2d[:,:])
print('aarray2d[:2,1:] : \n', array2d[:2,1:])
print('aarray2d[:2,0] : \n', array2d[:2,0]) # column 0에 있는 element만 출력

array2d : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
aarray2d[0:2,0:2] : 
 [[1 2]
 [4 5]]
aarray2d[1:3,1:3] : 
 [[5 6]
 [8 9]]
aarray2d[1:3,:] : 
 [[4 5 6]
 [7 8 9]]
aarray2d[:,:] : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
aarray2d[:2,1:] : 
 [[2 3]
 [5 6]]
aarray2d[:2,0] : 
 [1 4]


In [37]:
print(array2d[0]) # 1차원 row ndarray 반환
print(array2d[1])
print('aarray2d[0].shape :', array2d[0].shape, 'aarray2d[1].shape :', array2d[1].shape) 

[1 2 3]
[4 5 6]
aarray2d[0].shape : (3,) aarray2d[1].shape : (3,)


3. **팬시 인덱싱(Fancy indexing)** : 일정한 인덱싱 집합을 list 혹은 ndarray 형태로 지정해 해당하는 데이터의 ndarray를 반환



In [64]:
array1d = np.arange(1,10)
array2d = array1d.reshape(3,3)
print(array2d)

array3 = array2d[[0,1],2]
print('array2d[[0,1],2] => ', array3.tolist()) # [a02, a12] => [3,6]

array4 = array2d[[0,1],0:2]
print('array2d[[0,1],0:2] => ', array4.tolist()) # [[a00, a01], [a10, a11]] => [[1,2],[4,5]]

array5 = array2d[[0,1]]
print('array2d[[0,1]] => ', array5.tolist()) # [[a00, a01, a02], [a10, a11, a12]] => [[1,2,3],[4,5,6]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[[0,1],2] =>  [3, 6]
array2d[[0,1],0:2] =>  [[1, 2], [4, 5]]
array2d[[0,1]] =>  [[1, 2, 3], [4, 5, 6]]


4. **불린 인덱싱(Boolean indexing)** : 특정 조건에 해당하는지 True/False 값 인덱싱 집합을 기반으로 True에 해당하는 인덱스 위치에 있는 데이터의 ndarray를 반환
 + 조건 필터링과 검색을 동시에 할 수 있어 자주 사용된다.
 + for 반복문이나 if else 조건문보다 훨씬 간단하게 할 수 있다.
 + `array1d > 5`와 같이 조건식을 쓰면 True/False로 이루어진 ndarray 객체가 반환된다.
 ```python
array_new = array[조건식]
 ```

In [68]:
array1d = np.arange(1,10)
# 데이터값이 5보다 큰 데이터만 추출
array3 = array1d[array1d > 5]
print('array1d > 5인 boolean indexing 결과 값 : ', array3)

array1d > 5인 boolean indexing 결과 값 :  [6 7 8 9]


In [66]:
array1d > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [70]:
boolean_indexes = np.array([False, False, False, False, False, True, True, True, True])
array3 = array1d[boolean_indexes]
print('boolean 인덱스로 필터링 결과 : ', array3)

boolean 인덱스로 필터링 결과 :  [6 7 8 9]


In [71]:
# 직접 인덱스 집합을 만들어 대입한 것과 비교
indexes = np.array([5,6,7,8])
array4 = array1d[indexes]
print('일반 인덱스로 필터링한 결과 : ', array4)

일반 인덱스로 필터링한 결과 :  [6 7 8 9]


### | 행렬의 정렬 - sort()와 argsort()
___
- **행렬 정렬 : sort()**
  + `np.sort()` : 넘파이에서 sort()를 호출. 원래의 행렬을 변경하지 않고, 정렬된 행렬을 새로 반환.
  + `ndarray.sort()` : 행렬 자체에서 sort()를 호출. 원래의 행렬 자체를 정렬하며 반환 값은 None
  + **내림차순**으로 정렬하기 위해서는 **[::-1]**을 적용한다. (Ex) `np.sort()[::1]`
  + 2차원 이상의 행렬일 경우, **axis 축 값 설정**을 통해 row 방향 혹은 column 방향으로 정렬할 수 있다.


In [53]:
org_array = np.array([3,1,9,5])
print('원본 행렬 : ', org_array)

# np.sort()로 정렬
sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬', sort_array1)
print('np.sort() 호출 후 원본 행렬', org_array)

# ndarray.sort()로 정렬
sort_array2 = org_array.sort()
print('org_array.sort() 호출 후 반환된 정렬 행렬', sort_array2)
print('org_array.sort() 호출 후 원본 행렬', org_array)


원본 행렬 :  [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬 [1 3 5 9]
np.sort() 호출 후 원본 행렬 [3 1 9 5]
org_array.sort() 호출 후 반환된 정렬 행렬 None
org_array.sort() 호출 후 원본 행렬 [1 3 5 9]


In [55]:
# 내림차순으로 정렬
sort_array1_desc = np.sort(org_array)[::1]
print('내림차순으로 정렬', sort_array1_desc)

내림차순으로 정렬 [1 3 5 9]


In [56]:
# 2차원 행렬 정렬
array2d = np.array([[8,12],
                    [7,1]])
sort_array2d_axis0 = np.sort(array2d, axis = 0)
print('row 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis = 1)
print('column 방향으로 정렬:\n', sort_array2d_axis1)

row 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
column 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


- 정렬된 행렬의 인덱스를 반환하기 : **argsort()**
  + `np.argsort()` : 정렬 행렬의 원본 행렬 인덱스를 ndarry 형으로 반환
  + 넘파이의 ndarray는 메타 데이터를 가질 수 없기 때문에, 실제 값과 그 값이 뜻하는 메타 데이터를 별도의 ndarray에 가져야 한다. 이럴 때, argsort()를 활용하면 데이터 추출하기 편리하다.
    * 예를 들면 'A의 점수'를 저장할 때, A의 이름과 점수를 각각 저장해야 한다. 이때, 시험 성적순으로 학생 이름을 출력하고자 한다면 np.argsort()를 이용해 반환된 인덱스를 팬시 인덱스로 적용해 데이터를 추출할 수 있따.

In [58]:
org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array)
print(type(sort_indices)) # ndarray
print('행렬 정렬 시 원본 행렬의 인덱스 :', sort_indices) #[1 3 5 9]로 정렬되니까, 인덱스는 [1 0 3 2]
print(org_array) # 원본 행렬은 변하지 않음.

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스 : [1 0 3 2]
[3 1 9 5]


In [60]:
# 내림차순으로 정렬 : [::-1]
org_array = np.array([3,1,9,5])
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스 :', sort_indices_desc) #[9 5 3 1]로 정렬되니까, 인덱스는 [2 3 0 1]

행렬 내림차순 정렬 시 원본 행렬의 인덱스 : [2 3 0 1]


In [62]:
# argsort()를 이용하여 성적순으로 이름 정렬하기
import numpy as np

name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array = np.array([78, 95, 84, 98, 88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력', name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스 [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력 ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


### | 선형대수학 연산 - 행렬 곱(Matrix Mutiplication)과 전치 행렬(Transposed Matrix) 구하기
___
- **Matrix Multiplication** : `np.dot`을 이용



In [51]:
A = np.array([[1,2,3],
              [4,5,6]])
B = np.array([[7,8],
              [9,10],
              [11,12]])
dot_product = np.dot(A,B)
print('행렬 곱 결과: \n', dot_product)

행렬 곱 결과: 
 [[ 58  64]
 [139 154]]


- **Transposed Matrix** : `transpose()`를 이용


In [52]:
A = np.array([[1,2],
              [3,4]])
transpose_mat = np.transpose(A)
print('A의 전치행렬: \n', transpose_mat)

A의 전치행렬: 
 [[1 3]
 [2 4]]
