<a href="https://colab.research.google.com/github/Dkepffl/2022-1-ESAA/blob/main/Assignment/Assignment0314.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [ ]:
Z = np.arange('2016-07', '2016-08', dtype = 'datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [ ]:
def compute_above(A,B):
  A= A.astype(float)
  B= B.astype(float)
  np.add(A, B, out = B) # Elementwise addition
  np.divide(A, 2, out = A) # output을 A에 저장.
  np.negative(A, out = A)
  np.multiply(A, B, out = A)
  return A

A = np.random.randint(1,10, size = (3,3))
B = np.random.randint(1,10, size = (3,3))
print(compute_above(A,B))

[[-56.   -1.   -6. ]
 [-10.5  -3.  -58.5]
 [-40.  -49.  -15. ]]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [ ]:
Z = np.random.uniform(0,10,10)
print(Z)

print(Z - Z%1) # 소수부분을 뺀다.
print(Z // 1) 
print(np.floor(Z)) # 내림 함수
print(Z.astype(int)) # 형변환

[3.52289409 7.30742401 5.1990697  3.66122056 4.81164952 3.25188489
 9.41669546 0.55742309 7.06991458 8.45954962]
[3. 7. 5. 3. 4. 3. 9. 0. 7. 8.]
[3. 7. 5. 3. 4. 3. 9. 0. 7. 8.]
[3. 7. 5. 3. 4. 3. 9. 0. 7. 8.]
[3 7 5 3 4 3 9 0 7 8]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
Z = np.arange(5)
I = np.zeros((5,5))
np.add(I, Z, out= I)
print(I)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [ ]:
def gene_10int():
  X = np.random.randint(0,100, size = 10)
  return X

print(gene_10int())

[76 28 12 16 75 27 42 20 36  4]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [ ]:
Z = np.random.random(10)
print(Z)

[0.19907766 0.69785925 0.27317757 0.52696312 0.53338761 0.09260116
 0.57043515 0.8246693  0.95673288 0.57916521]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.0390216  0.17063945 0.18831734 0.28006073 0.56698482 0.6277131
 0.70259308 0.76362302 0.79879399 0.87275575]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [ ]:
Z = np.arange(10)
np.add.reduce(Z)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [ ]:
A = np.random.randint(1,10, size = (3,3))
B = np.random.randint(1,10, size = (3,3))
print('A :\n',A,'\n B :\n', B)

np.equal(A,B)

A :
 [[5 2 9]
 [2 7 8]
 [9 7 9]] 
 B :
 [[7 4 9]
 [6 9 5]
 [5 6 5]]


array([[False, False,  True],
       [False, False, False],
       [False, False, False]])

#### 43. Make an array immutable (read-only) (★★☆)

In [ ]:
Z = np.zeros(10)
Z.flags.writeable = False # 읽기 전용
Z[0] = 1 # assignment destination is read-only

ValueError: ignored

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [ ]:
Z = np.random.randint(1,10, size = (10,2))
X = Z[:,0] # column1 = X
Y = Z[:,1] # column2 = Y

# convert to polar
R = np.sqrt(X**2 + Y**2)
T = np.arctan2(Y,X) # angle
for i in range(10):
  print('({} , {})'.format(R[i],T[i]))

(9.219544457292887 , 0.21866894587394195)
(7.615773105863909 , 1.1659045405098132)
(10.63014581273465 , 0.8519663271732721)
(3.1622776601683795 , 1.2490457723982544)
(5.0990195135927845 , 1.373400766945016)
(8.06225774829855 , 0.5191461142465229)
(10.0 , 0.6435011087932844)
(5.830951894845301 , 0.5404195002705842)
(10.0 , 0.9272952180016122)
(10.816653826391969 , 0.5880026035475675)


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [ ]:
Z = np.random.randint(1,10, size = 10)
print(Z)
Z[Z.argmax()] = 0
print(Z)

[7 8 1 5 2 1 9 8 6 1]
[7 8 1 5 2 1 0 8 6 1]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [4]:
Z = np.zeros((5,5),[('x', float),('y',float)])
Z['x'],Z['y'] = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
# arrange()함수는 간격을 지정하고, linspace()함수는 구간의 개수를 지정함.
# linspace는 끝값을 포함함.
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [108]:
Y = np.array([[9, 5, 7, 9],
 [7, 4, 3, 1],
 [1, 2, 5, 9],
 [1, 8, 3, 7,]])
X = Y + np.random.randint(1,10, size = (4,4))
C = 1/np.subtract(X,Y)

print(C)

[[0.11111111 0.125      0.125      0.33333333]
 [0.11111111 1.         0.125      0.33333333]
 [0.33333333 1.         0.5        0.25      ]
 [0.16666667 0.14285714 0.25       1.        ]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [ ]:
for dtype in [np.int8, np.int32, np.int64]:
  print(np.iinfo(dtype).min)
  print(np.iinfo(dtype).max)
for dtype in [ np.float32, np.float64]:
  print(np.finfo(dtype).min)
  print(np.finfo(dtype).max)
  print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [ ]:
np.set_printoptions(threshold = float("inf"))
Z = np.zeros((16,16))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [ ]:
Z = np.arange(100)
v = np.random.uniform(0,100)
print(v)
index = (np.abs(Z-v)).argmin() # 절댓값이 가장 작은 index를 찾아 넣는다.
print(Z[index])

60.2207130541499
60


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [78]:
Z = np.zeros(10, [('position', [('x', float),('y',float)]), 
                  ('color', [('r', float),
                             ('g', float),
                             ('b', float)])]) # np.zeros()를 통해 빈 배열 생성
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [110]:
Z = np.random.random((10,2))
X, Y = np.atleast_2d(Z[:,0],Z[:,1])
D = np.sqrt((X-X.T)**2 + (Y-Y.T)**2) # ???
print(D)

[[0.         0.8162558  0.50120559 1.06017911 0.82624544 0.18797187
  0.93457171 0.16434868 0.29666489 0.36425106]
 [0.8162558  0.         0.54412428 0.36561593 0.48653094 0.66738971
  0.40312575 0.65877579 0.75478508 0.45548012]
 [0.50120559 0.54412428 0.         0.6343809  0.33224363 0.31558809
  0.86295197 0.42991693 0.27254463 0.36398777]
 [1.06017911 0.36561593 0.6343809  0.         0.37000632 0.88163452
  0.72960105 0.92442624 0.90227063 0.73779737]
 [0.82624544 0.48653094 0.33224363 0.37000632 0.         0.63831502
  0.88465256 0.72988331 0.60017612 0.59723073]
 [0.18797187 0.66738971 0.31558809 0.88163452 0.63831502 0.
  0.85276218 0.14569319 0.17635227 0.24908625]
 [0.93457171 0.40312575 0.86295197 0.72960105 0.88465256 0.85276218
  0.         0.77362209 0.99563638 0.6038716 ]
 [0.16434868 0.65877579 0.42991693 0.92442624 0.72988331 0.14569319
  0.77362209 0.         0.3197819  0.20354053]
 [0.29666489 0.75478508 0.27254463 0.90227063 0.60017612 0.17635227
  0.99563638 0.31978

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [31]:
Z = np.random.rand(1,10)*100
Z = Z.astype(np.int32)
print(Z)

[[74 57 56 36 91  6 13 60 43 25]]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [35]:
from io import StringIO
s = StringIO("""
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
""")
Z = np.genfromtxt(s, delimiter= ',', dtype = np.int, filling_values = 0) # filling_values으로 빈칸을 0으로 설정함. 없으면 -1로 들어감.
print(Z)

[[ 1  2  3  4  5]
 [ 6  0  0  7  8]
 [ 0  0  9 10 11]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  import sys


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [41]:
# enumerate() : index와 element를 tuple로 만들어줌
Z = np.random.randint(1,10,size=(5,5))
for i, value in np.ndenumerate(Z): # numpy 버전의 enumerate()
  print(i, value)

for i in np.ndindex(Z.shape): # Z.shpae = (5,5)
  print(i, Z[i])

(0, 0) 2
(0, 1) 5
(0, 2) 5
(0, 3) 7
(0, 4) 4
(1, 0) 8
(1, 1) 4
(1, 2) 1
(1, 3) 9
(1, 4) 7
(2, 0) 9
(2, 1) 9
(2, 2) 7
(2, 3) 6
(2, 4) 2
(3, 0) 2
(3, 1) 3
(3, 2) 2
(3, 3) 4
(3, 4) 2
(4, 0) 2
(4, 1) 3
(4, 2) 5
(4, 3) 2
(4, 4) 6
(0, 0) 2
(0, 1) 5
(0, 2) 5
(0, 3) 7
(0, 4) 4
(1, 0) 8
(1, 1) 4
(1, 2) 1
(1, 3) 9
(1, 4) 7
(2, 0) 9
(2, 1) 9
(2, 2) 7
(2, 3) 6
(2, 4) 2
(3, 0) 2
(3, 1) 3
(3, 2) 2
(3, 3) 4
(3, 4) 2
(4, 0) 2
(4, 1) 3
(4, 2) 5
(4, 3) 2
(4, 4) 6


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [85]:
# 정규분포인 array 만들기
X = np.random.normal(0,1,(4,5))
print(X)

[[-0.88549315 -1.10457948  0.93286635  2.059838   -0.93493796]
 [-1.61299022  0.52706972 -1.55110074  0.32961334 -1.13652654]
 [-0.3384906   0.32097078 -0.60230802  1.54472836  0.64703408]
 [ 0.59321721  0.4380245   1.35778902  1.20451128  1.35179619]]


#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [75]:
def rand_lota(n,p):
  Z = np.zeros((n,n))
  a = np.random.choice(range(n*n), p, replace = False) # a는 element가 p개인 array
  np.put(Z, a, 2)
  print(Z)

rand_lota(10,4)

[[0. 0. 0. 0. 0. 0. 0. 2. 0. 0.]
 [0. 2. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [2. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 2. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [81]:
np.random.seed(20) 
X = np.random.randint(1,10,size = (5,3))
print(X)
print(X.mean(axis = 1))

[[4 5 7]
 [8 3 1]
 [7 9 6]
 [4 1 7]
 [7 1 6]]
[5.33333333 4.         7.33333333 4.         4.66666667]


#### 59. How to sort an array by the nth column? (★★☆)

In [3]:
np.random.seed(20) 
X = np.random.randint(1,10,size = (3,3))
print(X)
X = X[X[:,0].argsort()] # col1을 기준으로 크기순대로 정렬
print(X)
X = X[X[:,1].argsort()] # col2을 기준으로 크기순대로 정렬
print(X)
X = X[X[:,2].argsort()] # col3을 기준으로 크기순대로 정렬
print(X)

[[4 5 7]
 [8 3 1]
 [7 9 6]]
[[4 5 7]
 [7 9 6]
 [8 3 1]]
[[8 3 1]
 [4 5 7]
 [7 9 6]]
[[8 3 1]
 [7 9 6]
 [4 5 7]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [15]:
Z = np.random.randint(0,3,(5,5))
print(Z)
print(np.isnan(Z).any(axis=1)) # 행을 축으로 NaN값이 있으면 True, 없으면 False

[[1 1 2 1 2]
 [0 2 0 1 0]
 [1 0 0 1 2]
 [2 1 1 0 1]
 [1 0 0 2 2]]
[False False False False False]


#### 61. Find the nearest value from a given value in an array (★★☆)

In [23]:
Z = np.random.uniform(0,1,10)
print(Z)
z = 0.5 # 지정된 값
near = Z.flat[np.abs(Z-z).argmin()] # flat : latten method를 적용한 후의 1차 array에 indexing을 한다.
print(near)

[0.75871913 0.85880213 0.68166244 0.92987793 0.74206941 0.69191226
 0.29494636 0.65548598 0.39357368 0.90070834]
0.3935736786310503


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [36]:
A = np.random.randint(0,10,(1,3))
B = np.random.randint(0,10,(3,1))
it = np.nditer([A,B,None]) # 배열의 모든 요소 방문
print(A)
print(B)
for x, y, z in it:
  z[...] = x + y # '...'는 생략 부호. slicing 할 때':'과 비슷한 용도로 사용 가능
print(it.operands[2]) # operands : tuple of operands. None의 인덱스가 2라서 2

[[2 6 0]]
[[9]
 [3]
 [6]]
[[11 15  9]
 [ 5  9  3]
 [ 8 12  6]]


#### 63. Create an array class that has a name attribute (★★☆)

In [44]:
class NamedArray(np.ndarray):
  def __new__(cls, array, name = "no name"): # 인스턴스가 소멸될 때 호출되는 함수 : 소멸자 __func__
    obj = np.asarray(array).view(cls)
    obj.name = name
    return obj
  
  def __array_finalize__(self, obj): 
    if obj is None: return 
    self.info = getattr(obj, 'name', "no name") # object에 존재하는 속성의 값을 가져온다.

Z = NamedArray(np.arange(10), "range_10") # "range_10"가 없으면 "no name"이 출력
print(Z.name)


no name


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [48]:
Z = np.ones(10) # a given vector
I = np.random.randint(0,len(Z), 20) # a second vector
print(Z)
print(I)
print(np.bincount(I, minlength = len(Z)))
Z += np.bincount(I, minlength = len(Z)) # numpy.bincount(arr, weights = None, min_len = 0) : 각각의 빈도수를 카운트하는데 사용되는 메소드
print(Z)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1 3 1 5 2 7 2 1 2 2 4 2 6 1 6 8 5 3 2 8]
[0 4 6 2 1 2 2 1 2 0]
[1. 5. 7. 3. 2. 3. 3. 2. 3. 1.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [56]:
X = np.arange(7)
I = np.random.randint(0,len(X), len(X))
F = np.bincount(I,X)
print(X)
print(I)
print(F)

[0 1 2 3 4 5 6]
[4 0 3 4 5 6 3]
[1. 0. 0. 8. 3. 4. 5.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [77]:
np.random.seed(20) 
w, h = 16, 16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte) # (w, h, 3) 크기의 byte 이미지 생성. I는 3차원 배열
F = I[...,0]*(256**2) + I[...,1]*256 + I[...,2] # '...' 대신 ':,:'를 넣어도 됨. 
n = len(np.unique(F)) # np.unique : 중복된 요소를 제외하고 고유한 요소들을 리턴
print(n) # 3차원 RGB 이미지의 고유 색상의 개수 계산

8
