<a href="https://colab.research.google.com/github/Dkepffl/2022-1-ESAA/blob/main/Statistical_Methods_for_Big_Data_Analysis/Lecture0315.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Lecture 2022/03/15

### 1) 리스트(List)

In [16]:
# list and indexing
sample_list = [1, 2, 3, 4, 5]
print(sample_list[0])
print(sample_list[-2])

1
4


In [12]:
# Slicing
print(sample_list[0:4])
print(sample_list[0:])
print(sample_list[:])
print(sample_list[:3])
print(sample_list[::-1]) # reverse
print(sample_list[1::-1]) # first two items, reversed
print(sample_list[:-3:-1]) # the last two items, reversed
print(sample_list[-3::-1]) # everything except the last two ites, reversed. [3, 2, 1] 

[1, 2, 3, 4]
[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5]
[1, 2, 3]
[5, 4, 3, 2, 1]
[2, 1]
[5, 4]
[3, 2, 1]


In [17]:
# List Operation
print(len(sample_list))

del(sample_list[1])
print(sample_list)

5
[1, 3, 4, 5]


In [19]:
list1 = [1,2,3]
list2 = [4, 5]

list3 = list1 + list2
print(list3)

print(list1*2) # list 반복

[1, 2, 3, 4, 5]
[1, 2, 3, 1, 2, 3]


In [23]:
list_a = [1, 2, 3, 4, 5]
list_a.append(6)
list_a.insert(1,1.5)
print(list_a)

[1, 1.5, 2, 3, 4, 5, 6]


In [24]:
list_b = [5, 2, 6, 100, 400, 300]
list_b.sort()
print(list_b)
list_b.sort(reverse = True)
print(list_b)

[2, 5, 6, 100, 300, 400]
[400, 300, 100, 6, 5, 2]


### 2) 배열(array)

In [25]:
import numpy as np

In [28]:
sample_array = np.array([1, 2, 3, 4, 5])
print(sample_array)

sample_array2d = np. array([[1,2,3,4,5],
                            [6,7,8,9,10]])
print(sample_array2d)

[1 2 3 4 5]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [29]:
type(sample_array)

numpy.ndarray

Note : list는 원소의 자료형이 달라도 되지만, array는 모두 같은 자료형이어야 한다.

In [36]:
print(sample_array[0:2])
print(sample_array2d[0,4])
print(sample_array2d[0:2,0:4])

[1 2]
5
[[1 2 3 4]
 [6 7 8 9]]


In [37]:
arr = np.array([[1.1 ,2,3],
                [4,5,6]])
print(arr.dtype)

float64


In [39]:
# elementwise operation
print(arr*arr)
print(arr + arr)
print(1/arr * 10)

[[ 1.21  4.    9.  ]
 [16.   25.   36.  ]]
[[ 2.2  4.   6. ]
 [ 8.  10.  12. ]]
[[9.09090909 5.         3.33333333]
 [2.5        2.         1.66666667]]


In [40]:
arr1 = np. array([1,2,3])
arr2 = np.array([[4,5,6],[7,8,9]])
arr3 = np.array([1, 2, 3, 4])

print(arr1 + arr2) # 긴쪽에 맞춰서 연산
print(arr1 + arr3) # 1차원 벡터의 길이가 다른 경우에는 Error 발생

[[ 5  7  9]
 [ 8 10 12]]


ValueError: ignored

### 3) 데이터 프레임(dataframe)

In [41]:
import pandas as pd

In [46]:
df1 = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]])
print(df1)
df1

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9


0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [47]:
data = {
    'age' : [20, 23, 45],
    'height' : [183, 92, 175],
    'weight' : [77, 83, 65],
    'gender' : ["M", "M", "F"] # character vector
}
indexName = ['슈퍼맨', '스파이더맨', '배트맨']

df2 = pd.DataFrame(data, index = indexName)
print(df2)

       age  height  weight gender
슈퍼맨     20     183      77      M
스파이더맨   23      92      83      M
배트맨     45     175      65      F


In [50]:
import numpy as np
import pandas as pd

In [49]:
np.random.seed(2) # seed : seed를 설정해두면 실행을 여러 번해도 생성된 난수가 변하지 않음.

df = pd.DataFrame(np.random.randint(1, 10, size=(3,5)))
df

0  1  2  3  4
0  9  9  7  3  9
1  8  3  2  6  5
2  5  6  8  4  7

In [52]:
np.random.seed(2022)

df = pd.DataFrame(np.random.randint(10,22,size = (4,5)),
                  index = ['a','b', 'c', 'd'],
                  columns = ['A','B', 'C', 'D', 'E'])
df

A   B   C   D   E
a  10  11  11  10  17
b  18  12  18  10  15
c  19  11  21  21  13
d  18  21  10  13  16

In [54]:
df.head(n=3) # 처음 3개의 행

A   B   C   D   E
a  10  11  11  10  17
b  18  12  18  10  15
c  19  11  21  21  13

In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, a to d
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       4 non-null      int64
 1   B       4 non-null      int64
 2   C       4 non-null      int64
 3   D       4 non-null      int64
 4   E       4 non-null      int64
dtypes: int64(5)
memory usage: 364.0+ bytes


In [56]:
df.shape

(4, 5)

In [59]:
print(df['A'])
print(df[['A','C']])

a    10
b    18
c    19
d    18
Name: A, dtype: int64
    A   C
a  10  11
b  18  18
c  19  21
d  18  10


In [60]:
df.B

a    11
b    12
c    11
d    21
Name: B, dtype: int64

In [61]:
df.drop('A',axis = 1) # 지정한 열(axis =1)만 빼고 데이터를 추출

B   C   D   E
a  11  11  10  17
b  12  18  10  15
c  11  21  21  13
d  21  10  13  16

In [63]:
df.drop('a',axis = 0) # 지정한 행(axis =0)만 빼고 데이터를 추출

A   B   C   D   E
b  18  12  18  10  15
c  19  11  21  21  13
d  18  21  10  13  16

In [64]:
df[df["A"]>15] # 조건문을 이용하여 데이터 추출

A   B   C   D   E
b  18  12  18  10  15
c  19  11  21  21  13
d  18  21  10  13  16

In [65]:
df[(df["A"]>15) | (df["B"]>17)] # and는 &, or는 |

A   B   C   D   E
b  18  12  18  10  15
c  19  11  21  21  13
d  18  21  10  13  16

In [69]:
df.query('index == "a"')

A   B   C   D   E
a  10  11  11  10  17

In [70]:
df.loc["a"]

A    10
B    11
C    11
D    10
E    17
Name: a, dtype: int64

In [71]:
df.iloc[0,0]

10

- **df.info()** 데이터프레임에 관련된 기본 데이터를 반환
- **df.head()** 데이터프레임의 첫 5열을 반환(default는 5줄)
- **df.columns** 데이터프레임의 열 레이블 반환
- **df.ndim** 차원을 나타내는 int를 반환
- **df.shape** 데이터프레임의 크기를 나타내는 튜플을 반환
- **df.size** 데이터프레임의 크기를 나타내는 int를 반환
- **df.dtypes** 데이터프레임에서 dtype(데이터 타입)을 반환
- **df.describe()** R의 summary 함수와 같은 기능을 함.


- CSV(Comma Separated Value) : 보통 Excel로 열리지만 텍스트 에디터 파일에서 열린다(기본 포맷이 comma로 구분되는 텍스트 파일)


In [72]:
# 중요
%%writefile sample.csv 
c1, c2, c3
1, 1.11, one
2, 2.22, two
3, 3.33, three


Writing sample.csv


In [ ]:
pd.read_csv('sample.csv')