<a href="https://colab.research.google.com/github/Dkepffl/2022-1-ESAA/blob/main/Session/Session_220314_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
print(np.__version__)
np.show_config()

1.21.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSS

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
A = np.zeros(10)

#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
A.itemsize # 배열의 메모리크기 확인. 원소의 사이즈를 byte 단위로 확인 가능

8

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [3]:
np.info(numpy.add)

NameError: ignored

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
A = np.zeros(10)
A[4] = 1
print(A)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
A = np.arange(10,50)
print(A)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
A = np.arange(50)
A = A[::-1] # 배열의 값을 역순으로 반환
print(A)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
mat1 = np.arange(9).reshape(3,3) # .reshpae()를 통해 배열의 차원 변경
print(mat1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
A = np.nonzero( [1,2,0,0,4,0]) # np.where()을 사용해도 됨
print(A)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [ ]:
I_3 = np.identity(3)
print(I_3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [ ]:
arr_3D = np.random.random((3,3,3))
print(arr_3D)

[[[0.49468659 0.2812325  0.90395876]
  [0.01759214 0.8757804  0.59270958]
  [0.77873945 0.18809908 0.59216728]]

 [[0.04542755 0.91173071 0.0880681 ]
  [0.85708461 0.38080047 0.54930845]
  [0.67049896 0.20271775 0.57457337]]

 [[0.08740909 0.17068814 0.84193563]
  [0.46865115 0.49816004 0.94431963]
  [0.55746378 0.48886951 0.76820934]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [4]:
array10 = np.random.random((10,10))

print(array10.max())
print(array10.min())

0.9989118787472806
0.005667784739919579


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [5]:
A = np.random.random(30)
print(np.mean(A))

0.5361379373699209


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
def array(a,b):
  x = np.ones((a,b))
  x[1:-1,1:-1]=0
  return x

print(array(3,4))

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [ ]:
def border_add(a,b):
  array = np.ones((a,b))
  array[2:a-1,2:b-1] = 2
  array = np.pad(array, pad_width=1, mode='constant', constant_values=0) # pad_with = 각 axis의 edge에 채워진 값의 수
  return array

border_add(4,3)

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

# nan(Not a Number) 어떤 연산이든 관계없이 NaN으로 반환
# False. NaN이라도 항상 같은 NaN이 아님
# False NaN은 숫자가 아니기 때문에 비교할 수 없음
# nan 
# True 
# False. 부동소수점 때문

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [ ]:
A = np.array([1,2,3,4])
mat = np.diag(A, k=-1) # 'k = '으로 시작 index 설정 가능
print(mat)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
Z = np.zeros((8,8))
Z[1::2,::2]=1 #fancy indexing : 시퀀스 객체[start:end:step]
Z[::2,1::2]=1
print(Z)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [ ]:
Z = np.unravel_index(99,(6,7,8)) # 해당하는 수의 index를 tuple 형태로 보내줌
print(Z) # 100번째이면 99 입력해야 하는 거 아닌지?

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [ ]:
print(np.tile([[0,1],[1,0]],(4,4))) # numpy.tile(A,reps) : reps = (a,b) 

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [6]:
Z = np.random.random((5,5))
Z = (Z - np.mean(Z)) / (np.std(Z))
print(Z)

[[-0.45979419 -1.20067713  0.75352837 -0.46148885  0.7505272 ]
 [-1.49948957 -1.50392261  0.64404305  0.86853245  1.2399953 ]
 [ 1.34649314 -1.05603447 -1.62374629 -0.79439615 -0.1937897 ]
 [ 0.07538539 -0.05459519  1.0174594   1.10115807 -0.53473171]
 [ 0.42796961 -1.14914197 -0.57931028  1.38707798  1.49894814]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [ ]:
color=np.dtype([("r",np.ubyte),
                ("g",np.ubyte),
                ("b",np.ubyte),
                ("a",np.ubyte)]) # numpy.dtype. u = unsign

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
A = np.random.randint(1, 10, size=(5, 3))
B = np.random.randint(1, 10, size=(3, 2))
print(np.dot(A,B))

[[85 51]
 [85 73]
 [95 75]
 [92 79]
 [39 40]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
X = np.arange(20)
X[(3 < X) & (X < 8)] *= -1
print(X)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10 11 12 13 14 15 16 17 18 19]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [7]:
print(sum(range(5),-1)) # sum(iterable, start=0), 1+2+3+4+(-1)
from numpy import *
print(sum(range(5),-1)) # -1은 axis를 의미함

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
# Z**Z : Z[i] ** Z[i]를 한 vector가 나온다.
# 2 << Z >> 2 : bit shift
# 4번째 줄은 복소수 연산이 가능함을 의미
# 복수의 조건일 때, |이나 &로 연결해야지 직접 연결하면 안 됨.

# Only Z<Z>Z is illegal

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [8]:
# nan. 0으로 나눌 수 없음
# 0 몫만 계산하니까 0
# np.nan은 NaN의 부동 소수점 표현. [-9.22337204e+18]

#### 29. How to round away from zero a float array ? (★☆☆)

In [ ]:
Z = np.random.uniform(-10, 10, 10)
print(Z)
print(np.round(Z)) # np.around(array, decimals=b)

[ 8.37498006  2.9026685   2.45214265  3.75316956  2.05973878  5.05670094
  4.99421771 -0.57287389  3.18858298  9.65949836]
[ 8.  3.  2.  4.  2.  5.  5. -1.  3. 10.]


#### 30. How to find common values between two arrays? (★☆☆)

In [ ]:
Z1 = np.arange(10)
Z2 = np.arange(20)
np.intersect1d(Z1,Z2) # 두 개의 array의 교집합을 정렬하여 반환.

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
# Suicide mode on
defaults=np.seterr(all="ignore") # 오류 발생 시 아무 action으로 취하지 않음

# Back to sanity
_=np.seterr(**defaults)

# Equivalently with a context manager
with np.errstate(all="ignore"): # 경고 메세지를 표시X
    np.arange(3) / 0

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [9]:
# '1j == NaN', False 
# np.emath : outdata와 input data가 다를 때 사용

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [ ]:
yesterday=np.datetime64('today')-np.timedelta64(1)
today=np.datetime64('today')
tomorrow=np.datetime64('today')+np.timedelta64(1)

print(yesterday)
print(today)
print(tomorrow)

2022-03-13
2022-03-14
2022-03-15
