<a href="https://colab.research.google.com/github/Dkepffl/2022-1-ESAA/blob/main/Session/Session_220314_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
print(np.__version__)
np.show_config()

1.21.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSS

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
A = np.zeros(10)

#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
A.itemsize

8

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
import numpy; numpy.info(numpy.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
A = np.zeros(10)
A[4] = 1
print(A)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
A = np.arange(10,50)
print(A)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
A = np.arange(50)
A = A[::-1]
print(A)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
mat1 = np.arange(9).reshape(3,3)
print(mat1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
A = np.nonzero( [1,2,0,0,4,0] )
print(A)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [ ]:
I_3 = np.identity(3)
print(I_3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [ ]:
arr_3D = np.random.random((3,3,3))
print(arr_3D)

[[[0.49468659 0.2812325  0.90395876]
  [0.01759214 0.8757804  0.59270958]
  [0.77873945 0.18809908 0.59216728]]

 [[0.04542755 0.91173071 0.0880681 ]
  [0.85708461 0.38080047 0.54930845]
  [0.67049896 0.20271775 0.57457337]]

 [[0.08740909 0.17068814 0.84193563]
  [0.46865115 0.49816004 0.94431963]
  [0.55746378 0.48886951 0.76820934]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [ ]:
array10 = np.random.random((10,10))
print(array10)
print(array10.max())
print(array10.min())

[[0.84753151 0.19866751 0.26903057 0.82942053 0.24873407 0.36486369
  0.0590446  0.31619297 0.254183   0.69008465]
 [0.44611009 0.63604726 0.55428436 0.32788376 0.54675666 0.32875809
  0.27808585 0.72342698 0.03584347 0.14054477]
 [0.72158368 0.22288262 0.1473559  0.05672263 0.1977167  0.41885604
  0.04834892 0.03560149 0.8190108  0.12713397]
 [0.05847538 0.79918259 0.16367786 0.75341909 0.63899195 0.99237448
  0.4569216  0.89496088 0.3597591  0.9770807 ]
 [0.46293804 0.20311542 0.933941   0.75336589 0.32731922 0.29364202
  0.27424859 0.94108946 0.96025427 0.41498504]
 [0.64128835 0.02562104 0.80157681 0.17431579 0.53643498 0.57877457
  0.60861268 0.11522018 0.99557032 0.4677726 ]
 [0.1160961  0.57788169 0.49788095 0.94171276 0.08112415 0.46087682
  0.1910602  0.81812249 0.85235584 0.78654257]
 [0.25863097 0.20247121 0.18825304 0.67245908 0.26016391 0.54367271
  0.4791619  0.76230047 0.58193689 0.06661085]
 [0.42344056 0.32337656 0.5333621  0.63652185 0.39458276 0.22627898
  0.17237675

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [ ]:
A = np.random.random(30)
print(A)
print(np.mean(A))

[0.58028426 0.15919062 0.62689611 0.26348125 0.76478008 0.42829496
 0.24022339 0.70206569 0.26087921 0.22313002 0.42306099 0.50821915
 0.16581853 0.39659214 0.40710868 0.05802127 0.63085161 0.01573304
 0.4935572  0.99946886 0.3069957  0.83161193 0.44149091 0.62884624
 0.18039206 0.3539677  0.03183861 0.47903346 0.51127985 0.15208458]
0.4088399372613704


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
def array(a,b):
  x=np.ones((a,b))
  x[1:-1,1:-1]=0
  return x

print(array(3,4))

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [ ]:
def border_add(a,b):
  array = np.ones((a,b))
  array[2:a-1,2:b-1] = 2
  array = np.pad(array, pad_width=1, mode='constant', constant_values=0)
  return array

border_add(4,3)

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

# nan(Not a Number) 어떤 연산이든 관계없이 NaN으로 반환
# False. NaN이라도 항상 같은 NaN이 아님
# False NaN은 숫자가 아니기 때문에 비교할 수 없음
# nan 
# True 
# False. 부동소수점 때문

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [ ]:
A = np.array([1,2,3,4])
mat = np.diag(A, k=-1)
print(mat)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
Z = np.zeros((8,8))
Z[1::2,::2]=1
Z[::2,1::2]=1
print(Z)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [ ]:
Z = np.unravel_index(99,(6,7,8)) # 해당하는 수의 index를 tuple 형태로 보내줌
print(Z)

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [ ]:
print(np.tile([[0,1],[1,0]],(4,4)))

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [ ]:
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

[[ 0.2959964  -1.7213566   0.64238394  0.43132901  0.14725062]
 [ 1.1418155   0.55439    -1.71099108  1.35616899  0.27081763]
 [ 0.73365163  0.30417767 -1.4258269   1.22872388  0.40144011]
 [ 0.95598468 -1.11037956 -0.58038529 -0.57467729  1.11903897]
 [-0.73609947 -0.74820128  0.77716199  0.39576877 -2.14818234]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [ ]:
color=np.dtype([("r",np.ubyte),
                ("g",np.ubyte),
                ("b",np.ubyte),
                ("a",np.ubyte)])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
A = np.random.randint(1, 10, size=(5, 3))
B = np.random.randint(1, 10, size=(3, 2))
print(np.dot(A,B))

[[85 51]
 [85 73]
 [95 75]
 [92 79]
 [39 40]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
X = np.arange(20)
X[(3 < X) & (X < 8)] *= -1
print(X)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10 11 12 13 14 15 16 17 18 19]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1)) # 1+2+3+4+(-1)
from numpy import *
print(sum(range(5),-1)) # range(5)에 있는 수들 중 -1보다 큰 수들의 합

# 9
# 10

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
# Z**Z : Z[i] ** Z[i]를 한 vector가 나온다.
# 2 << Z >> 2 : bit shift

# Only Z<Z>Z is illegal

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
# nan. 0으로 나눌 수 없음
# 0 몫만 계상하니까 0
# [-9.22337204e+18]



nan
0
[-9.22337204e+18]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


#### 29. How to round away from zero a float array ? (★☆☆)

In [ ]:
Z = np.random.uniform(-10, 10, 10)
print(Z)
print(np.round(Z))

[ 8.37498006  2.9026685   2.45214265  3.75316956  2.05973878  5.05670094
  4.99421771 -0.57287389  3.18858298  9.65949836]
[ 8.  3.  2.  4.  2.  5.  5. -1.  3. 10.]


#### 30. How to find common values between two arrays? (★☆☆)

In [ ]:
Z1 = np.arange(10)
Z2 = np.arange(20)
np.intersect1d(Z1,Z2)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
# Suicide mode on
defaults=np.seterr(all="ignore")

# Back to sanity
_=np.seterr(**defaults)

# Equivalently with a context manager
with np.errstate(all="ignore"):
    np.arange(3) / 0

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
# '1j == NaN', False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [ ]:
yesterday=np.datetime64('today')-np.timedelta64(1)
today=np.datetime64('today')
tomorrow=np.datetime64('today')+np.timedelta64(1)

print(yesterday)
print(today)
print(tomorrow)

2022-03-13
2022-03-14
2022-03-15
